### ISSUE TITLE
Awesome Idea for a package. Have you considered merging this with the LaTeXStrings package?

### ISSUE THREAD

**Issue by rodonn** [scheinerman/LatexPrint.jl#1]
I think some of the code you have written would be a nice addition to the existing https://github.com/stevengj/LaTeXStrings.jl/blob/master/README.md

Have you considered merging your code with theirs?

One nice feature they have is that it makes it easy to output LaTeX formulas from code in an IJulia notebook.

**Comment by scheinerman** [comment]
Thanks. I'll drop a note to them to see if they want to add this to their package. I think the purposes are related, but sort of opposite in function. The LaTeXStrings package makes it easy for a user to type LaTeX code into Julia for later display in Julia. This package is used to turn a Julia object into LaTeX for pasting into a LaTeX document.

**Comment by rodonn** [comment]
Thanks again for making a cool package!
