### ISSUE TITLE
fails on printing 'nothing' 

### ISSUE THREAD

**Issue by mosiman** [scheinerman/LatexPrint.jl#11]
For me, it's not that big a deal. I may have a hand at submitting a PR if I've got time, but I thought i'd leave this here.

**Comment by scheinerman** [comment]
I tried and see this:
```julia
julia> lap(nothing)
ERROR: ArgumentError: `nothing` should not be printed; use `show`, `repr`, or custom output instead.
```
So the question is: Is this a "good" error. Since `nothing` is not supposed to be printed, maybe leave this alone?  In any case, it would be simple enough to fix this if we want by adding this:
```julia
LatexPrint.latex_form(x::Nothing)="nothing"
```
Or is there a better LaTeX representation for `nothing`?

**Comment by mosiman** [comment]
Here’s an example where I would think to have to print nothing:

```julia
julia> x = [1,2,3,4,5,6];
julia> y = [try x[i] - x[i-1] catch(BoundsError) nothing end for i in 1:6];
julia> tabular(hcat(x,y))
```

Of course there are other “N/A” data types (missing, null, etc) so I’m not quite sure what would be the best behaviour. In this scenario, I think the intuitive behaviour would be to simply print literally nothing (maybe like `\,` in latex, which inserts a blank space).

**Comment by scheinerman** [comment]
I've updated the code to handle `nothing`. The output I chose was `\mathrm{nothing}` but I also provide the function `set_nothing` so it's easy to change that to something you prefer (an example is shown in the `README`). Thanks for the suggestion.
