### ISSUE TITLE
hlines between tabular rows

### ISSUE THREAD

**Issue by sebastiantroue** [scheinerman/LatexPrint.jl#12]
Do you thought about adding an option in the tabular() function which offers the opportunity to print "\hline" after each row such that LaTex inserts horizontal separation lines between the rows in the table?

**Comment by scheinerman** [comment]
I'm not sure the best way to do that. The `tabular` function is not one that I expect users to call directly. I could create a global value `NEWLINE` that is, by default `\\` but that could be changed to `\\ \hline` by the user by a function named `set_newline`. But then both matrices and vectors would behave the same. Thoughts?

**Comment by sebastiantroue** [comment]
I am not sure why users should not call the `tabular` functions, as far as i see there are no other functions using them, could you explain? 
I would suggest a Bool flag as a parameter for the `tabular` function and then change a `NEWLINE` variable locally based on this Bool. I think so because users may want to change this setting multiple times depending on the table they want to create and this solution seems to be more suitable for these cases. 
If you solve the problem as described this also would not affect vectors/matrices at all. I didnt had  the `\hlines` in the array environments in mind but I dont see the necessity for horizontal lines in LaTex matrices and vectors.

**Comment by scheinerman** [comment]
OK. I'll try to put this in. Please note that I really don't understand the whole "release" process and have had a terrible time with it. So when updated, you may need to update/install this as a development package.

**Comment by sebastiantroue** [comment]
Ok thanks

**Comment by scheinerman** [comment]
Please see the new version. `tabular` now takes two optional *named* optional arguments: `alignment` to give the alignment string and `hlines` which (if `true`) appends `\hline` to all but the last row.
