### ISSUE TITLE
import Pkg; Pkg.add("LatexPrint")

### ISSUE THREAD

**Issue by janrpeters** [scheinerman/LatexPrint.jl#13]
I tried

import Pkg; Pkg.add("LatexPrint")

but I get

The following package names could not be resolved:
 * LatexPrint

Do I need to clone it?

**Comment by scheinerman** [comment]
Sorry you're having trouble. I really don't understand how all this package stuff works. I just use `Pkg.dev` because it never complains. Yeah, I suppose try `Pkg.clone` ... sorry!!

**Comment by janrpeters** [comment]
Just a suggestion: Please add the Installation instruction

pkg"add https://github.com/scheinerman/LatexPrint.jl"

such that I and other Julia Newbies directly understand how easy your 
really nice (non-registered) package can be added …

**Comment by scheinerman** [comment]
Thanks for the suggestion.
