### ISSUE TITLE
Option for controlling number of decimals for floats

### ISSUE THREAD

**Issue by rodonn** [scheinerman/LatexPrint.jl#4]
I think it would be helpful to have a global setting that controls the number of decimals to print when printing AbstractFloats.

If you don't mind, I could make an attempt at a pull request for this change.

**Comment by scheinerman** [comment]
I'm happy for your input. I'm a real "git minimalist" so I'm not 100% sure how "pull requests" work, but another choice is if you send me an updated source file, I can just upload that.

**Comment by mobius-eng** [comment]
I have this function

```julia
function convert_float(x :: T, precision = 5) where T <: AbstractFloat
    raw_str = string(x)
    precision_count = 0
    started_significant = false
    started_exponent = false
    res_out = IOBuffer()
    for c in raw_str
        if c == '-' || c == '+'
            print(res_out, c)
        elseif c == 'e' || c == 'f'
            print(res_out, "\\times 10^{")
            started_exponent = true
        elseif c == '.'
            print(res_out, c)
        elseif isdigit(c) && started_exponent
            print(res_out, c)
        else
            if c == '0' && (!started_significant)
                print(res_out, c)
            elseif c != '0' && (!started_significant)
                started_significant = true
                precision_count = 1
                print(res_out, c)
            elseif precision_count < precision
                precision_count += 1
                print(res_out, c)
            else
                continue
            end
        end
    end
    # clean up
    if started_exponent
        print(res_out, '}')
    end
    return String(take!(res_out))
end
```

as a drop-in replacement for `string(x)` call in `latex_form` for floats. I have also introduced `FLOAT_PRECISION` global to control the default precision, so the call is `convert_float(x, FLOAT_PRECISION)`.

NB. The function will try to print significant digits, not just a certain number of digits.

**Comment by scheinerman** [comment]
Thanks for this. I'm wondering if people would want all digits in some cases. So if your `FLOAT_PRECISION` is set to a negative value, then we default to `string(x)`?

**Comment by scheinerman** [comment]
Here's a concern. This function truncates but doesn't round. 
```
julia> x = 0.9999999999
0.9999999999

julia> convert_float(x)
"0.99999"
```
I think the output should be `"1.00000"` or `"1.0"` in this case.

**Comment by mobius-eng** [comment]
Yes, I discovered that flaw… The best option so far I can think of is to use Formatting and then use my function (maybe even simplify it) to convert the number to a nice LaTeX form.

**Comment by mobius-eng** [comment]
I have fixed it. And also made `tabular` to output to `IO` and not only `STDOUT`: this is handy in Jupyter as it's better to capture the output to pass it to `display("text/latex", x)`. Changes are [in the fork](https://github.com/mobius-eng/LatexPrint.jl). Not sure what's the best way to bring them back into the repo.

**Comment by scheinerman** [comment]
I am barely able to function in git, so I'm not really sure. Maybe just email me the changed files??
