### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by arnavs** [scheinerman/LatexPrint.jl#8]
Is this a registered package? Can't add it by name using `Pkg`

**Comment by scheinerman** [comment]
I thought it was registered. Are you using Julia 0.7 (or higher)?

**Comment by arnavs** [comment]
Hey @scheinerman, here's what I see- 

```
(v1.0) pkg> add LatexPrint
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
ERROR: The following package names could not be resolved:
 * LatexPrint (not found in project, manifest or registry)
Please specify by known `name=uuid`.

julia> versioninfo()
Julia Version 1.0.2
Commit d789231e99 (2018-11-08 20:11 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

**Comment by scheinerman** [comment]
I guess it's not registered then. I tried. So this should work:
```
(v1.0) pkg> add https://github.com/scheinerman/LatexPrint.jl.git
```

**Comment by arnavs** [comment]
Yeah, that works. It would be great if it'd be registered though (you can do that using the Attobot github integration). 

That way, we could include it in standalone package bundles like https://github.com/quantecon/quanteconlectureallpackages

**Comment by scheinerman** [comment]
I drafted a new release. We'll see if it gets picked up.

**Comment by arnavs** [comment]
Didn't seem to catch it. 

This is tricky b/c there's an old METADATA PR https://github.com/JuliaLang/METADATA.jl/pull/2105, but they're moving stuff to the new registry. 

cc @ararslan, do you think you could advise on what to do here? tl;dr package was registered in METADATA before, doesn't seem to be in the registry anymore, is invisible to Attobot.

**Comment by ararslan** [comment]
No idea at all. I'd recommend opening an issue on METADATA.

**Comment by ararslan** [comment]
It would be good to check whether Attobot is enabled for this repository.
